### ISSUE TITLE
Cannot find -lPYTHON_LIBRARY-NOTFOUND

### ISSUE THREAD

**Issue by NhatMinh2208** [nihofm/volren#1]
```
[  1%] Built target libglew_shared
[ 10%] Built target glfw
[ 79%] Built target imebra
[ 89%] Built target cppgl
[ 94%] Built target voldata
[ 95%] Built target voldata_serialize
[ 96%] Built target voldata_print
[ 97%] Linking CXX executable ../volren
/usr/bin/ld: cannot find -lPYTHON_LIBRARY-NOTFOUND
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/volren.dir/build.make:156: ../volren] Error 1
make[1]: *** [CMakeFiles/Makefile2:282: CMakeFiles/volren.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```
I got this error while trying to build the project. I don't know how to fix this since i already installed python on my machine.

**Comment by nihofm** [comment]
Hi,
Did you install both python and python-dev packages? Please try `sudo apt install python3-dev` or similar for your distro and see if the issue persists.

**Comment by NhatMinh2208** [comment]
Thank you! It okay by now. Turn out i have to delete the old build repository and re-built it from the start.
